### ISSUE TITLE
zhihu

### ISSUE THREAD

**Issue by ee-5** [primovist/ScriptsForSurge#2]
知乎去广告去不干净。

**Comment by primovist** [comment]
> 知乎去广告去不干净。

试试看添加rule-sets之后可以不可以。
另外这个是Surge用的，QX没测试和改写。

**Comment by ee-5** [comment]
感谢，加了这一段之后广告清干净了。
USER-AGENT,AVOS*,REJECT-TINYGIF
URL-REGEX,https://www.zhihu.com/api/v4/mcn/,REJECT-TINYGIF
URL-REGEX,https://api.zhihu.com/(ab|adx|drama|fringe|zst|commercial|ad-style-service|market/popover|search/(top|tab|preset)|.*(guide|recommendations|extended|featured-comment-ad)),REJECT-TINYGIF
AND,((USER-AGENT,osee2*), (NOT,((DOMAIN-SUFFIX,zhihu.com))), (NOT,((DOMAIN-SUFFIX,zhimg.com)))),REJECT-TINYGIF
