### ISSUE TITLE
smzdm

### ISSUE THREAD

**Issue by haluzt** [primovist/ScriptsForSurge#4]
什么值得买搜索后有横幅间广告，^https?:\/\/s-api\.smzdm\.com\/sou\/list;有些mp4的广告还是有，http://t.cn/A67n6O1d

**Comment by primovist** [comment]
> 什么值得买搜索后有横幅间广告，^https?:\/\/s-api\.smzdm\.com\/sou\/list;有些mp4的广告还是有，http://t.cn/A67n6O1d

已经完善相关正则

**Comment by haluzt** [comment]
quanx失效，能否帮忙适配下

**Comment by primovist** [comment]
> quanx失效，能否帮忙适配下

我没有QX哦，试试看用转换脚本然后自己改一下匹配规则呢？

**Comment by haluzt** [comment]
首页视频广告好像还有，网页抓包链接http://t.cn/A67n6O1d

**Comment by primovist** [comment]
> 首页视频广告好像还有，网页抓包链接http://t.cn/A67n6O1d

已更新，请测试后回复。谢谢。

**Comment by haluzt** [comment]
完美适配qx，谢谢

**Comment by haluzt** [comment]
商品详情评论区下面还有广告，能否帮忙去除
