### ISSUE TITLE
Bilibili新的广告

### ISSUE THREAD

**Issue by Mon5ter777** [primovist/ScriptsForSurge#6]
如图，bilibili-我的页面内又出现了新的，会员购生效。
![IMG_8030](https://user-images.githubusercontent.com/62795820/81637623-65395100-9449-11ea-94e3-7af8f56aa2d5.PNG)

**Comment by primovist** [comment]
感谢反馈。晚上下班回去再修改。

发自我的iPhone

在 2020年5月12日，12:09，Mon5ter777 <notifications@github.com> 写道：

﻿

如图，bilibili-我的页面内又出现了新的，会员购生效。
[IMG_8030]<https://user-images.githubusercontent.com/62795820/81637623-65395100-9449-11ea-94e3-7af8f56aa2d5.PNG>
