### ISSUE TITLE
什么值得买去广告误杀搜索页面筛选功能

### ISSUE THREAD

**Issue by vhvg** [primovist/ScriptsForSurge#7]
目前脚本针对 `pattern=^https?:\/\/(s|h(aojia|omepage)|(articl|baik)e)-api\.smzdm\.com\/(home|sou)` 应用SMZDM.js，会拦截 `https:\/\/s-api.smzdm.com\/sou\/list_filter?` 进而使搜索页面的筛选功能失效。

尝试修改 `pattern=^https?:\/\/(s|h(aojia|omepage)|(articl|baik)e)-api\.smzdm\.com\/(home|sou)(?!\/list_filter)`  后可解决此问题。

**Comment by primovist** [comment]
谢谢反馈
